using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using System.Linq;

namespace MiniProject.Models
{
    public class MockData
    {
        public List<AudioBook> audioBooks { get; } = new List<AudioBook>
        {
            new AudioBook { Author = "Sarah J. Maas", Title = "A Court of Thorns and Roses", BookGenre = Book.Genre.Fantasy, SingleNarration = true, GraphicAudio = true, Trope = new List<string> {"Found Family", "Enemies-to-Lovers", "Fated Love" },   },
            new AudioBook { Author = "Damien R. James", Title = "The Lone Hero 1", BookGenre = Book.Genre.Action, Subplot = new List<string> { "Conflict", "Adventure", "Personal Struggle", "World Building", }, Trope = new List<string> { "Lone Hero / One-Man Army", "High Stakes", "Relentless Antagonist", "Showdown", "Daring Escape / Chase Sequence" } },
            new AudioBook { Author = "Damien R. James", Title = "The Lone Hero 2", BookGenre = Book.Genre.Action,  Subplot = new List<string> { "Conflict", "Adventure", "Personal Struggle", "World Building", }, Trope = new List<string> { "Lone Hero / One-Man Army", "High Stakes", "Relentless Antagonist", "Showdown", "Daring Escape / Chase Sequence" } },
            new AudioBook { Author = "Dakota Krout", Title = "World's Only Hero", BookGenre = Book.Genre.Action, Subplot = new List<string> { "Conflict", "Adventure", "Personal Struggle", "World Building", }, Trope = new List<string> {"Lone Hero / One-Man Army", "High Stakes", "Race Against Time", "Underdog Victory", "Mysterious Past"} },
            new AudioBook { Author = "Suzanne Brockmann", Title = "Forever Blue", BookGenre = Book.Genre.Action, Subplot = new List<string> { "Romance", "Conflict", "Adventure", }, Trope = new List<string> { "Reluctant Hero", "High Stakes", "Showdown", "Daring Escape / Chase Sequence" } },
            new AudioBook { Author = "Brett Vogeler", Title = "The Reluctant Hero", BookGenre = Book.Genre.Action, Subplot = new List<string> { "Conflict", "Personal Struggle", }, Trope = new List<string> { "Reluctant Hero", "High Stakes", "Race Against Time", "Relentless Antagonist" } },
            new AudioBook { Author = "Angela Douglas", Title = "The Mentor", BookGenre = Book.Genre.Action, Subplot = new List<string> { "Conflict", "Side Character", "Personal Struggle", }, Trope = new List<string> { "Mentor-Student Dynamic", "Relentless Antagonist", "High Stakes", "Mysterious Past" } },
            new AudioBook { Author = "Andre Tkachev", Title = "The Strongest Student", BookGenre = Book.Genre.Action, Subplot = new List<string> { "Conflict", "Adventure", "Personal Struggle", "World Building", "Side Character" }, Trope = new List<string> { "Mentor-Student Dynamic", "Underdog Victory", "Showdown"} },
            new AudioBook { Author = "Boris Romanovsky", Title = "A Student Wants to Live", BookGenre = Book.Genre.Action, Subplot = new List<string> { "Conflict", "Adventure", "Personal Struggle", }, Trope = new List<string> { "Underdog Victory", "Relentless Antagonist", "Race Against Time" } },
            new AudioBook { Author = "Michael Benfante", Title = "Reluctant Hero", BookGenre = Book.Genre.Action, Subplot = new List<string> { "Conflict", "Adventure", "Personal Struggle", }, Trope = new List<string> { "Reluctant Hero", "Underdog Victory", "High Stakes" } },
            new AudioBook { Author = "Summer Lee", Title = "The Reluctant Hero Trilogy", BookGenre = Book.Genre.Action, Subplot = new List<string> { "Conflict", "Adventure", "Personal Struggle", "Side Character", }, Trope = new List<string> { "Reluctant Hero", "High Stakes", "Showdown", "Race Against Time" } },
            new AudioBook { Author = "Frank Herbert", Title = "Dune", BookGenre = Book.Genre.SciFi, Subplot = new List<string> { "Political Intrigue", "Space", "Special Destiny" }, Trope = new List<string> { "Chosen One", "Oppressive Empire", "Prophecy", } },
            new AudioBook { Author = "Patrick Rothfuss", Title = "The Name of the Wind", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Romantasy", "Action & Adventure"}, Trope = new List<string> { "Secret Society", "Magical School" } },
            new AudioBook { Author = "Rebecca Yarros", Title = "Fourth Wing", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Romantasy", "Action & Adventure", "High Fantasy" }, Trope = new List<string> { "Chosen One", "Magic School", "Secret Society" } },
            new AudioBook { Author = "Caroline Peckham & Susanne Valenti", Title = "Zodiac Academy: The Awakening", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Urban Fantasy", "Romantasy", "Action & Adventure" }, Trope = new List<string> { "Magic School", "Secret Society", "Fated Love" }},
            new AudioBook { Author = "Naomi Novik", Title = "A Deadly Education", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Dark Fantasy", "Magic School", "Action & Adventure" }, Trope = new List<string> { "Reluctant / Outcast Hero", "Magic School", "Secret Lair" } },
            new AudioBook { Author = "Olivie Blake", Title = "The Atlas Six", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Contemporary Fantasy", "Dark Fantasy" }, Trope = new List<string> { "Secret Society", "Antihero", "Magical Objects" }},
            new AudioBook { Author = "Leigh Bardugo", Title = "Shadow and Bone", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "High Fantasy", "Epic Fantasy", "Action & Adventure" }, Trope = new List<string> { "Chosen One", "Secret Royalty", "Magical World" }},
            new AudioBook { Author = "R.F. Kuang", Title = "The Poppy War", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Dark Fantasy", "Historical Fantasy", "Action & Adventure" }, Trope = new List<string> { "Magic School", "Reluctant / Outcast Hero", "Prophecy" }},
            new AudioBook { Author = "Kass Morgan & Danielle Paige", Title = "The Ravens", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Urban Fantasy", "Dark Fantasy" }, Trope = new List<string> { "Secret Society", "Magic School", "Paranormal Fantasy" } },
            new AudioBook { Author = "Isabella Kamal", Title = "The Temple of Persephone", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Regency, Medieval, or Victorian Romance", "Ancient Civilization", "Adventure" }, Trope = new List<string> { "Historical Figures", "Marriage of Convenience", "Cultural & Social Conflict" }},
            new AudioBook { Author = "Lisa Kleypas", Title = "The Devil in Winter", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Regency, Medieval, or Victorian Romance", "Gothic", "Crime" }, Trope = new List<string> { "Marriage of Convenience", "Progressive Characters", "Evil Antagonist" }},
            new AudioBook { Author = "Jennifer N. Brown", Title = "The Lost Book of Elizabeth Barton", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Mystery", "Biographical", "Regency, Medieval, or Victorian Romance" }, Trope = new List<string> { "Historical Figures", "Dual Narratives", "Cultural & Social Conflict" }},
            new AudioBook { Author = "Sadeqa Johnson", Title = "Keeper of Lost Children", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Saga", "War", "Crime" }, Trope = new List<string> { "Hero from Nothing", "Times are Changing", "Minor Characters with Big Impacts" }},
            new AudioBook { Author = "Ian McEwan", Title = "Atonement", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "War", "Mystery", "Gothic", "Crime" }, Trope = new List<string> { "Dual Narratives", "Cultural & Social Conflict", "Evil Antagonist" }},
            new AudioBook { Author = "Larry McMurtry", Title = "Lonesome Dove", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Western", "Adventure", "Pioneer" }, Trope = new List<string> { "Western Expansion", "Hero from Nothing", "Minor Characters with Big Impacts" }},
            new AudioBook { Author = "Cormac McCarthy", Title = "Blood Meridian", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Western", "War", "Adventure" }, Trope = new List<string> { "Evil Antagonist", "Cultural & Social Conflict", "Hero from Nothing" }},
            new AudioBook { Author = "Shirley Jackson", Title = "The Haunting of Hill House", BookGenre = Book.Genre.Horror, Subplot = new List<string> { "Ghost / Supernatural", "Gothic", "Psychological" }, Trope = new List<string> { "Haunted House", "Isolated Setting", "Abandoned Places", "Nightmare That Might Be Real" }},
            new AudioBook { Author = "Stephen King", Title = "The Shining", BookGenre = Book.Genre.Horror, Subplot = new List<string> { "Psychological", "Ghost / Supernatural", "Gothic" }, Trope = new List<string> { "Isolated Setting", "Evil Child / Creepy Kid", "Haunted House", "Inclement Nighttime Weather" }},
            new AudioBook { Author = "Silvia Moreno-Garcia", Title = "Mexican Gothic",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Gothic", "Psychological", "Dark Fantasy" },Trope = new List<string> { "Haunted House", "Ancient Evil", "Cursed Artifact / Object", "Small Town with Secrets" }},
            new AudioBook { Author = "Paul Tremblay",Title = "The Cabin at the End of the World",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Psychological", "Eco/Apocalysptic" },Trope = new List<string> { "Isolated Setting", "Final Person", "Mysterious Deaths", "Monsters in the Dark" }},
            new AudioBook { Author = "Stephen Graham Jones",Title = "The Only Good Indians",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Folk", "Psychological", "Dark Fantasy" },Trope = new List<string> { "Ancient Evil", "Monster as Metaphor", "Mysterious Deaths", "Nightmare That Might Be Real" }},
            new AudioBook { Author = "Josh Malerman",Title = "Bird Box",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Psychological", "Eco/Apocalysptic", "Dark Fantasy" },Trope = new List<string> { "Monsters in the Dark", "Final Person", "Isolated Setting", "Inclement Nighttime Weather" }},
            new AudioBook { Author = "Adam Nevill",Title = "The Ritual",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Folk", "Dark Fantasy", "Slasher" },Trope = new List<string> { "Ancient Evil", "Isolated Setting", "Monsters in the Dark", "Splitting Up" }},
            new AudioBook { Author = "Khaled Hosseini",Title = "The Kite Runner",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Conflict", "Character Growth / Transformation", "Fear or Vulnerability", "Backstory/Expository" },Trope = new List<string> { "Redemption Arc", "Quest / Journey", "Found Family" }},
            new AudioBook { Author = "Mai Nguyen",Title = "Cleo Dang Would Rather Be Dead",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Habit, Trait, or Addiction", "Fear or Vulnerability", "Character Growth / Transformation" },Trope = new List<string> { "Unreliable Narrator", "Slow Burn", "Found Family" }},
            new AudioBook { Author = "Hanya Yanagihara",Title = "A Little Life",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Fear or Vulnerability", "Character Growth / Transformation", "Backstory/Expository" },Trope = new List<string> { "Found Family", "Slow Burn", "Redemption Arc" }},
            new AudioBook { Author = "Sally Rooney",Title = "Normal People",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Romantic / Relational", "Conflict", "Parallel / Mirror" },Trope = new List<string> { "Slow Burn", "Enemies-to-Lovers", "Found Family" }},
            new AudioBook { Author = "Donna Tartt",Title = "The Goldfinch",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Backstory/Expository", "Fear or Vulnerability", "Two Worlds Collide" },Trope = new List<string> { "Unreliable Narrator", "Quest / Journey", "Redemption Arc" }},
            new AudioBook { Author = "Donna Tartt",Title = "The Secret History",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Conflict", "Fear or Vulnerability", "Parallel / Mirror" },Trope = new List<string> { "Unreliable Narrator", "Slow Burn", "Found Family", "Chosen One" }},

        }; 

        public List<EBook> eBooks { get; } = new List<EBook>
        {
            new EBook { Author = "Tahereh Mafi", Title = "Shatter Me", BookGenre = Book.Genre.YoungAdult, AvailableOnKU = false, BookLength = "339 pages", Publisher = "StoryTide", SpecialEditionOrBonusContent = false, Subplot = new List<string> { "Dystopian Rebellion" }, Trope = new List<string> { "Enemies-to-Lovers", "Hidden Powers"} },
            new EBook { Author = "Rebecca Yarros", Title = "Fourth Wing", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Romantasy", "Action & Adventure", "High Fantasy" }, Trope = new List<string> { "Chosen One", "Magic School", "Secret Society" } },
            new EBook { Author = "Caroline Peckham & Susanne Valenti", Title = "Zodiac Academy: The Awakening", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Urban Fantasy", "Romantasy", "Action & Adventure" }, Trope = new List<string> { "Magic School", "Secret Society", "Fated Love" }},
            new EBook { Author = "Naomi Novik", Title = "A Deadly Education", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Dark Fantasy", "Magic School", "Action & Adventure" }, Trope = new List<string> { "Reluctant / Outcast Hero", "Magic School", "Secret Lair" } },
            new EBook { Author = "Olivie Blake", Title = "The Atlas Six", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Contemporary Fantasy", "Dark Fantasy" }, Trope = new List<string> { "Secret Society", "Antihero", "Magical Objects" }},
            new EBook { Author = "Leigh Bardugo", Title = "Shadow and Bone", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "High Fantasy", "Epic Fantasy", "Action & Adventure" }, Trope = new List<string> { "Chosen One", "Secret Royalty", "Magical World" }},
            new EBook { Author = "R.F. Kuang", Title = "The Poppy War", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Dark Fantasy", "Historical Fantasy", "Action & Adventure" }, Trope = new List<string> { "Magic School", "Reluctant / Outcast Hero", "Prophecy" }},
            new EBook { Author = "Kass Morgan & Danielle Paige", Title = "The Ravens", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Urban Fantasy", "Dark Fantasy" }, Trope = new List<string> { "Secret Society", "Magic School", "Paranormal Fantasy" } },
            new EBook { Author = "Isabella Kamal", Title = "The Temple of Persephone", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Regency, Medieval, or Victorian Romance", "Ancient Civilization", "Adventure" }, Trope = new List<string> { "Historical Figures", "Marriage of Convenience", "Cultural & Social Conflict" }},
            new EBook { Author = "Lisa Kleypas", Title = "The Devil in Winter", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Regency, Medieval, or Victorian Romance", "Gothic", "Crime" }, Trope = new List<string> { "Marriage of Convenience", "Progressive Characters", "Evil Antagonist" }},
            new EBook { Author = "Jennifer N. Brown", Title = "The Lost Book of Elizabeth Barton", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Mystery", "Biographical", "Regency, Medieval, or Victorian Romance" }, Trope = new List<string> { "Historical Figures", "Dual Narratives", "Cultural & Social Conflict" }},
            new EBook { Author = "Sadeqa Johnson", Title = "Keeper of Lost Children", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Saga", "War", "Crime" }, Trope = new List<string> { "Hero from Nothing", "Times are Changing", "Minor Characters with Big Impacts" }},
            new EBook { Author = "Ian McEwan", Title = "Atonement", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "War", "Mystery", "Gothic", "Crime" }, Trope = new List<string> { "Dual Narratives", "Cultural & Social Conflict", "Evil Antagonist" }},
            new EBook { Author = "Larry McMurtry", Title = "Lonesome Dove", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Western", "Adventure", "Pioneer" }, Trope = new List<string> { "Western Expansion", "Hero from Nothing", "Minor Characters with Big Impacts" }},
            new EBook { Author = "Cormac McCarthy", Title = "Blood Meridian", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Western", "War", "Adventure" }, Trope = new List<string> { "Evil Antagonist", "Cultural & Social Conflict", "Hero from Nothing" }},
            new EBook { Author = "Shirley Jackson", Title = "The Haunting of Hill House", BookGenre = Book.Genre.Horror, Subplot = new List<string> { "Ghost / Supernatural", "Gothic", "Psychological" }, Trope = new List<string> { "Haunted House", "Isolated Setting", "Abandoned Places", "Nightmare That Might Be Real" }},
            new EBook { Author = "Stephen King", Title = "The Shining", BookGenre = Book.Genre.Horror, Subplot = new List<string> { "Psychological", "Ghost / Supernatural", "Gothic" }, Trope = new List<string> { "Isolated Setting", "Evil Child / Creepy Kid", "Haunted House", "Inclement Nighttime Weather" }},
            new EBook { Author = "Silvia Moreno-Garcia", Title = "Mexican Gothic",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Gothic", "Psychological", "Dark Fantasy" },Trope = new List<string> { "Haunted House", "Ancient Evil", "Cursed Artifact / Object", "Small Town with Secrets" }},
            new EBook { Author = "Paul Tremblay",Title = "The Cabin at the End of the World",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Psychological", "Eco/Apocalysptic" },Trope = new List<string> { "Isolated Setting", "Final Person", "Mysterious Deaths", "Monsters in the Dark" }},
            new EBook { Author = "Stephen Graham Jones",Title = "The Only Good Indians",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Folk", "Psychological", "Dark Fantasy" },Trope = new List<string> { "Ancient Evil", "Monster as Metaphor", "Mysterious Deaths", "Nightmare That Might Be Real" }},
            new EBook { Author = "Josh Malerman",Title = "Bird Box",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Psychological", "Eco/Apocalysptic", "Dark Fantasy" },Trope = new List<string> { "Monsters in the Dark", "Final Person", "Isolated Setting", "Inclement Nighttime Weather" }},
            new EBook { Author = "Adam Nevill",Title = "The Ritual",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Folk", "Dark Fantasy", "Slasher" },Trope = new List<string> { "Ancient Evil", "Isolated Setting", "Monsters in the Dark", "Splitting Up" }},
            new EBook { Author = "Khaled Hosseini",Title = "The Kite Runner",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Conflict", "Character Growth / Transformation", "Fear or Vulnerability", "Backstory/Expository" },Trope = new List<string> { "Redemption Arc", "Quest / Journey", "Found Family" }},
            new EBook { Author = "Mai Nguyen",Title = "Cleo Dang Would Rather Be Dead",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Habit, Trait, or Addiction", "Fear or Vulnerability", "Character Growth / Transformation" },Trope = new List<string> { "Unreliable Narrator", "Slow Burn", "Found Family" }},
            new EBook { Author = "Hanya Yanagihara",Title = "A Little Life",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Fear or Vulnerability", "Character Growth / Transformation", "Backstory/Expository" },Trope = new List<string> { "Found Family", "Slow Burn", "Redemption Arc" }},
            new EBook { Author = "Sally Rooney",Title = "Normal People",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Romantic / Relational", "Conflict", "Parallel / Mirror" },Trope = new List<string> { "Slow Burn", "Enemies-to-Lovers", "Found Family" }},
            new EBook { Author = "Donna Tartt",Title = "The Goldfinch",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Backstory/Expository", "Fear or Vulnerability", "Two Worlds Collide" },Trope = new List<string> { "Unreliable Narrator", "Quest / Journey", "Redemption Arc" }},
            new EBook { Author = "Donna Tartt",Title = "The Secret History",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Conflict", "Fear or Vulnerability", "Parallel / Mirror" },Trope = new List<string> { "Unreliable Narrator", "Slow Burn", "Found Family", "Chosen One" }},
        };

        public List<PhysicalBook> physicalBooks { get; } = new List<PhysicalBook>
        {
            new PhysicalBook {Author = "Lindsey Richardson", Title = "Godsbane", BookGenre = Book.Genre.Fantasy, BookLength = "351 pages", PrintType = PhysicalBook.Type.Paperback, Publisher = "Fated Lore LLC", SpecialEditionOrBonusContent = false, Trope = new List<string> { "Bodyguard" } },
            new PhysicalBook { Author = "Rebecca Yarros", Title = "Fourth Wing", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Romantasy", "Action & Adventure", "High Fantasy" }, Trope = new List<string> { "Chosen One", "Magic School", "Secret Society" } },
            new PhysicalBook { Author = "Caroline Peckham & Susanne Valenti", Title = "Zodiac Academy: The Awakening", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Urban Fantasy", "Romantasy", "Action & Adventure" }, Trope = new List<string> { "Magic School", "Secret Society", "Fated Love" }},
            new PhysicalBook { Author = "Naomi Novik", Title = "A Deadly Education", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Dark Fantasy", "Magic School", "Action & Adventure" }, Trope = new List<string> { "Reluctant / Outcast Hero", "Magic School", "Secret Lair" } },
            new PhysicalBook { Author = "Olivie Blake", Title = "The Atlas Six", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Contemporary Fantasy", "Dark Fantasy" }, Trope = new List<string> { "Secret Society", "Antihero", "Magical Objects" }},
            new PhysicalBook { Author = "Leigh Bardugo", Title = "Shadow and Bone", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "High Fantasy", "Epic Fantasy", "Action & Adventure" }, Trope = new List<string> { "Chosen One", "Secret Royalty", "Magical World" }},
            new PhysicalBook { Author = "R.F. Kuang", Title = "The Poppy War", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Dark Fantasy", "Historical Fantasy", "Action & Adventure" }, Trope = new List<string> { "Magic School", "Reluctant / Outcast Hero", "Prophecy" }},
            new PhysicalBook { Author = "Kass Morgan & Danielle Paige", Title = "The Ravens", BookGenre = Book.Genre.Fantasy, Subplot = new List<string> { "Urban Fantasy", "Dark Fantasy" }, Trope = new List<string> { "Secret Society", "Magic School", "Paranormal Fantasy" } },
            new PhysicalBook { Author = "Isabella Kamal", Title = "The Temple of Persephone", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Regency, Medieval, or Victorian Romance", "Ancient Civilization", "Adventure" }, Trope = new List<string> { "Historical Figures", "Marriage of Convenience", "Cultural & Social Conflict" }},
            new PhysicalBook { Author = "Lisa Kleypas", Title = "The Devil in Winter", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Regency, Medieval, or Victorian Romance", "Gothic", "Crime" }, Trope = new List<string> { "Marriage of Convenience", "Progressive Characters", "Evil Antagonist" }},
            new PhysicalBook { Author = "Jennifer N. Brown", Title = "The Lost Book of Elizabeth Barton", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Mystery", "Biographical", "Regency, Medieval, or Victorian Romance" }, Trope = new List<string> { "Historical Figures", "Dual Narratives", "Cultural & Social Conflict" }},
            new PhysicalBook { Author = "Sadeqa Johnson", Title = "Keeper of Lost Children", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Saga", "War", "Crime" }, Trope = new List<string> { "Hero from Nothing", "Times are Changing", "Minor Characters with Big Impacts" }},
            new PhysicalBook { Author = "Ian McEwan", Title = "Atonement", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "War", "Mystery", "Gothic", "Crime" }, Trope = new List<string> { "Dual Narratives", "Cultural & Social Conflict", "Evil Antagonist" }},
            new PhysicalBook { Author = "Larry McMurtry", Title = "Lonesome Dove", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Western", "Adventure", "Pioneer" }, Trope = new List<string> { "Western Expansion", "Hero from Nothing", "Minor Characters with Big Impacts" }},
            new PhysicalBook { Author = "Cormac McCarthy", Title = "Blood Meridian", BookGenre = Book.Genre.HistoricalFiction, Subplot = new List<string> { "Western", "War", "Adventure" }, Trope = new List<string> { "Evil Antagonist", "Cultural & Social Conflict", "Hero from Nothing" }},
            new PhysicalBook { Author = "Shirley Jackson", Title = "The Haunting of Hill House", BookGenre = Book.Genre.Horror, Subplot = new List<string> { "Ghost / Supernatural", "Gothic", "Psychological" }, Trope = new List<string> { "Haunted House", "Isolated Setting", "Abandoned Places", "Nightmare That Might Be Real" }},
            new PhysicalBook { Author = "Stephen King", Title = "The Shining", BookGenre = Book.Genre.Horror, Subplot = new List<string> { "Psychological", "Ghost / Supernatural", "Gothic" }, Trope = new List<string> { "Isolated Setting", "Evil Child / Creepy Kid", "Haunted House", "Inclement Nighttime Weather" }},
            new PhysicalBook { Author = "Silvia Moreno-Garcia", Title = "Mexican Gothic",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Gothic", "Psychological", "Dark Fantasy" },Trope = new List<string> { "Haunted House", "Ancient Evil", "Cursed Artifact / Object", "Small Town with Secrets" }},
            new PhysicalBook { Author = "Paul Tremblay",Title = "The Cabin at the End of the World",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Psychological", "Eco/Apocalysptic" },Trope = new List<string> { "Isolated Setting", "Final Person", "Mysterious Deaths", "Monsters in the Dark" }},
            new PhysicalBook { Author = "Stephen Graham Jones",Title = "The Only Good Indians",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Folk", "Psychological", "Dark Fantasy" },Trope = new List<string> { "Ancient Evil", "Monster as Metaphor", "Mysterious Deaths", "Nightmare That Might Be Real" }},
            new PhysicalBook { Author = "Josh Malerman",Title = "Bird Box",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Psychological", "Eco/Apocalysptic", "Dark Fantasy" },Trope = new List<string> { "Monsters in the Dark", "Final Person", "Isolated Setting", "Inclement Nighttime Weather" }},
            new PhysicalBook { Author = "Adam Nevill",Title = "The Ritual",BookGenre = Book.Genre.Horror,Subplot = new List<string> { "Folk", "Dark Fantasy", "Slasher" },Trope = new List<string> { "Ancient Evil", "Isolated Setting", "Monsters in the Dark", "Splitting Up" }},
            new PhysicalBook { Author = "Khaled Hosseini",Title = "The Kite Runner",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Conflict", "Character Growth / Transformation", "Fear or Vulnerability", "Backstory/Expository" },Trope = new List<string> { "Redemption Arc", "Quest / Journey", "Found Family" }},
            new PhysicalBook { Author = "Mai Nguyen",Title = "Cleo Dang Would Rather Be Dead",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Habit, Trait, or Addiction", "Fear or Vulnerability", "Character Growth / Transformation" },Trope = new List<string> { "Unreliable Narrator", "Slow Burn", "Found Family" }},
            new PhysicalBook { Author = "Hanya Yanagihara",Title = "A Little Life",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Fear or Vulnerability", "Character Growth / Transformation", "Backstory/Expository" },Trope = new List<string> { "Found Family", "Slow Burn", "Redemption Arc" }},
            new PhysicalBook { Author = "Sally Rooney",Title = "Normal People",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Romantic / Relational", "Conflict", "Parallel / Mirror" },Trope = new List<string> { "Slow Burn", "Enemies-to-Lovers", "Found Family" }},
            new PhysicalBook { Author = "Donna Tartt",Title = "The Goldfinch",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Backstory/Expository", "Fear or Vulnerability", "Two Worlds Collide" },Trope = new List<string> { "Unreliable Narrator", "Quest / Journey", "Redemption Arc" }},
            new PhysicalBook { Author = "Donna Tartt",Title = "The Secret History",BookGenre = Book.Genre.LiteraryFiction,Subplot = new List<string> { "Conflict", "Fear or Vulnerability", "Parallel / Mirror" },Trope = new List<string> { "Unreliable Narrator", "Slow Burn", "Found Family", "Chosen One" }},
        };

        // Centralized collection of all books as Book instances to avoid repeating casts elsewhere
        public List<Book> AllBooks => audioBooks.Concat<Book>(eBooks).Concat(physicalBooks).ToList();

    }
}
